export const SET_GAME_STARTED = 'SET_GAME_STARTED';
export const SET_INSTRUCTIONS_EXPANDED = 'SET_INSTRUCTIONS_EXPANDED';

export const DECK = {
  FETCH_SUCCESS: 'DECK_FETCH_SUCCESS',
  FETCH_ERROR: 'DECK_FETCH_ERROR',
  FETCH_REQUEST: 'DECK_FETCH_REQUEST',
  DRAW_CARD_REQUEST: 'DRAW_CARD_REQUEST',
  DRAW_CARD_ERROR: 'DRAW_CARD_ERROR',
  DRAW_CARD_SUCCESS: 'DRAW_CARD_SUCCESS'
}
